let lessons = [
    {
        id: 1001,
        subject: "Mathematics",
        description: "Mathematics Class for all students",
        image: "images/maths.png",
        location: "M01",
        price: 2000,
        spaces: 5,
    },
    {
        id: 1002,
        subject: "English",
        description: "English Class for all students",
        image: "images/english.png",
        location: "E07",
        price: 1500,
        spaces: 6,
    },
    {
        id: 1003,
        subject: "Science",
        description: "Science Class for all students",
        image: "images/science.png",
        location: "M03",
        price: 3000,
        spaces: 8,
    },
    {
        id: 1004,
        subject: "Classics",
        description: "Classics Class for all students",
        image: "images/classics.png",
        location: "E20",
        price: 2500,
        spaces: 5,
    },
    {
        id: 1005,
        subject: "Geography",
        description: "Geography Class for all students",
        image: "images/geography.png",
        location: "G05",
        price: 1800,
        spaces: 9,
    },
    {
        id: 1006,
        subject: "Art",
        description: "Art Class for all students",
        image: "images/art.png",
        location: "A06",
        price: 2200,
        spaces: 5,
    },
    {
        id: 1007,
        subject: "Music",
        description: "Music Class for all students",
        image: "images/music.png",
        location: "M07",
        price: 2300,
        spaces: 5,
    },
    {
        id: 1009,
        subject: "Computer Science",
        description: "CS Class for all students",
        image: "images/computer.png",
        location: "C09",
        price: 2800,
        spaces: 11,
    },
    {
        id: 1010,
        subject: "Biology",
        description: "Biology Class for all students",
        image: "images/biology.png",
        location: "S10",
        price: 2600,
        spaces: 6,
    },
    {
        id: 1011,
        subject: "Chemistry",
        description: "Chemistry Class for all students",
        image: "images/chemistry.png",
        location: "S11",
        price: 2700,
        spaces: 5,
    },
    {
        id: 1012,
        subject: "Physics",
        description: "Physics Class for all students",
        image: "images/physics.png",
        location: "S12",
        price: 2900,
        spaces: 5,
    },
    {
        id: 1013,
        subject: "Surayt",
        description: "Assyrian Neo-Aramaic Class for all students",
        image: "images/assyrian_flag.png",
        location: "E13",
        price: 2400,
        spaces: 25,
    },
]